# -*- coding: utf-8 -*-
from django.urls import path

from .views.clients import (
    ClientDetailView,
    ClientsFilteredListView,
    ClientSignUpView,
    ClientsListView,
    ClientUpdateView,
)
from .views.flat import (
    FlatCreateView,
    FlatDeleteView,
    FlatDetailView,
    FlatFilteredListView,
    FlatListView,
    FlatUpdateView,
)
from .views.house import (
    CreateHouseView,
    DeleteHouseView,
    GetHouseInfoView,
    HouseDetailView,
    HouseFilteredListView,
    HouseListView,
    UpdateHouseView,
)
from .views.indications import (
    CounterIndicationsFilteredList,
    CounterIndicationsList,
    CreateIndication,
    CreateIndicationForFlat,
    CreateNewIndication,
    IndicationDetail,
    IndicationsFilteredList,
    IndicationsList,
    UpdateIndication,
)
from .views.other import GetRoleView
from .views.personal import PersonalAccountFilteredList, PersonalAccountListView
from .views.system_settings import (
    CopyTariffView,
    CreatePaymentArticleView,
    CreateTariffView,
    DeletePaymentArticleView,
    DeleteTariffView,
    GetMeasureView,
    ListPaymentArticleView,
    PaymentDetailView,
    PersonalDeleteView,
    PersonalDetailView,
    PersonalFilterView,
    PersonalListView,
    PersonalSignUpView,
    PersonalUpdateView,
    RolesListView,
    ServicesView,
    TariffDetail,
    TariffListView,
    UpdatePaymentArticleView,
    UpdateTariffView,
    get_measure_options,
)
from .views.website import (
    AboutUsView,
    ContactSiteView,
    DeleteDocsView,
    DeletePhotoView,
    MainPageView,
    SiteServicesView,
    TariffSiteView,
)

urlpatterns = [
    path("services/", ServicesView.as_view(), name="services"),
    path("tariffs/", TariffListView.as_view(), name="tariffs"),
    path("tariffs/<int:pk>/", TariffDetail.as_view(), name="tariff_detail"),
    path("tariffs/create/", CreateTariffView.as_view(), name="tariff_create"),
    path("tariffs-update/<int:pk>/", UpdateTariffView.as_view(), name="tariffs_update"),
    path("tariffs-copy/<int:pk>/", CopyTariffView.as_view(), name="tariffs_copy"),
    path("tariff-delete/<int:pk>/", DeleteTariffView.as_view(), name="tariff_delete"),
    path("get-measure/<int:pk>/", GetMeasureView.as_view(), name="get_measure"),
    path("get-role/<int:pk>/", GetRoleView.as_view(), name="get_role"),
    path("get_measure/", get_measure_options, name="get_measure_ajax"),
    path("personals/", PersonalListView.as_view(), name="personals"),
    path("personal-add/", PersonalSignUpView.as_view(), name="personal_add"),
    path(
        "personal-detail/<int:pk>/",
        PersonalDetailView.as_view(),
        name="personal_detail",
    ),
    path(
        "personal-update/<int:pk>/",
        PersonalUpdateView.as_view(),
        name="personal_update",
    ),
    path(
        "personal-delete/<int:pk>/",
        PersonalDeleteView.as_view(),
        name="personal_delete",
    ),
    path("personal-filter/", PersonalFilterView.as_view(), name="personal_filter"),
    path("payment/", PaymentDetailView.as_view(), name="payment"),
    path("articel-payments/", ListPaymentArticleView.as_view(), name="article_payments"),
    path(
        "articel-payments/create/",
        CreatePaymentArticleView.as_view(),
        name="article_payment_create",
    ),
    path(
        "articel-payments/update/<int:pk>/",
        UpdatePaymentArticleView.as_view(),
        name="article_payment_update",
    ),
    path(
        "articel-payments/delete/<int:pk>/",
        DeletePaymentArticleView.as_view(),
        name="article_payment_delete",
    ),
    path("roles/", RolesListView.as_view(), name="roles"),
    path("manage-site/main-page/", MainPageView.as_view(), name="main_page_update"),
    path("manage-site/about-page/", AboutUsView.as_view(), name="about_us"),
    path(
        "manage-site/delete-photo/<int:pk>/",
        DeletePhotoView.as_view(),
        name="delete_photo",
    ),
    path(
        "manage-site/delete-document/<int:pk>/",
        DeleteDocsView.as_view(),
        name="delete_docs",
    ),
    path("manage-site/services-page/", SiteServicesView.as_view(), name="services_page"),
    path("manage-site/tariffs-page/", TariffSiteView.as_view(), name="tariffs_page"),
    path("manage-site/contacts-page/", ContactSiteView.as_view(), name="contacts_page"),
    path("indicators/", IndicationsList.as_view(), name="indicators"),
    path(
        "indicators/filtered_indicators/",
        IndicationsFilteredList.as_view(),
        name="indicators_filtered",
    ),
    path(
        "indicators/counter-indicators/<str:flat>/<str:service>/",
        CounterIndicationsList.as_view(),
        name="counter_indicators",
    ),
    path(
        "indicators/filtered-counter-indicators/<str:flat>/",
        CounterIndicationsFilteredList.as_view(),
        name="filtered_counter_indicators",
    ),
    path("indicators/add", CreateIndication.as_view(), name="add_indicator"),
    path(
        "indicators/add_new/<str:flat>/<str:service>/",
        CreateNewIndication.as_view(),
        name="add_new_indicator",
    ),
    path(
        "indicators/add_to_flat/<str:flat>/",
        CreateIndicationForFlat.as_view(),
        name="add_indication_to_flat",
    ),
    path(
        "indicators/update/<str:pk>",
        UpdateIndication.as_view(),
        name="update_indication",
    ),
    path(
        "indicators/detail/<str:pk>",
        IndicationDetail.as_view(),
        name="detail_indication",
    ),
    path("houses/", HouseListView.as_view(), name="houses"),
    path(
        "houses/filtered-house/",
        HouseFilteredListView.as_view(),
        name="filtered_houses",
    ),
    path("houses/add/", CreateHouseView.as_view(), name="create_house"),
    path("houses/detail/<int:pk>/", HouseDetailView.as_view(), name="house_detail"),
    path("houses/delete/<int:pk>/", DeleteHouseView.as_view(), name="house_delete"),
    path("houses/update/<int:pk>/", UpdateHouseView.as_view(), name="house_update"),
    path(
        "houses/get-house-info/<int:pk>/",
        GetHouseInfoView.as_view(),
        name="get_house_info",
    ),
    path(
        "personal-accounts/",
        PersonalAccountListView.as_view(),
        name="personal_accounts",
    ),
    path(
        "personal-accounts/filtered/",
        PersonalAccountFilteredList.as_view(),
        name="filtered_personal_accounts",
    ),
    path("clients/", ClientsListView.as_view(), name="clients"),
    path("clients/filtered/", ClientsFilteredListView.as_view(), name="clients_filtered"),
    path("clients/add/", ClientSignUpView.as_view(), name="clients_add"),
    path("clients/detail/<int:pk>/", ClientDetailView.as_view(), name="clients_detail"),
    path("clients/update/<int:pk>/", ClientUpdateView.as_view(), name="clients_update"),
    path("clients/delete/<int:pk>/", ClientSignUpView.as_view(), name="clients_delete"),
    path("flats/", FlatListView.as_view(), name="flats"),
    path("flats/filtered/", FlatFilteredListView.as_view(), name="flats_filtered"),
    path("flats/create/", FlatCreateView.as_view(), name="flats_create"),
    path("flats/detail/<int:pk>/", FlatDetailView.as_view(), name="flats_detail"),
    path("flats/update/<int:pk>/", FlatUpdateView.as_view(), name="flats_update"),
    path("flats/delete/<int:pk>/", FlatDeleteView.as_view(), name="flats_delete"),
]
