# -*- coding: utf-8 -*-
# Generated by Django 4.2.1 on 2024-05-06 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                max_length=19,
                validators=[
                    django.core.validators.MaxLengthValidator(19),
                    django.core.validators.MinLengthValidator(19),
                    django.core.validators.ProhibitNullCharactersValidator(),
                    django.core.validators.RegexValidator(
                        "^\\+38 \\(\\d{3}\\) \\d{3}-?\\d{2}-?\\d{2}$",
                        message="Неверно введён номер телефона.Пример ввода: +38 (093) 123-12-34",
                    ),
                ],
                verbose_name="Номер телефона",
            ),
        ),
    ]
