# -*- coding: utf-8 -*-
# Generated by Django 4.2.1 on 2024-05-15 23:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0002_alter_customuser_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="phone",
            field=models.CharField(
                max_length=19,
                validators=[
                    django.core.validators.MaxLengthValidator(19),
                    django.core.validators.MinLengthValidator(19),
                    django.core.validators.ProhibitNullCharactersValidator(),
                    django.core.validators.RegexValidator(
                        "^\\+38 \\(\\d{3}\\) \\d{3}-?\\d{2}-?\\d{2}$",
                        message="Неверно введён номер телефона.Пример ввода: +38 (093) 123-12-34",
                    ),
                ],
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="measure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="admin_panel.measure",
                verbose_name="Ед. изм.",
            ),
        ),
    ]
